[build-system]
requires = ["setuptools>=75.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fraud-detection-platform"
version = "0.1.0"
description = "End-to-end machine learning platform for detecting fraudulent transactions."
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [
    { name = "Aditya Ojha" }
]

dependencies = [
    "numpy>=2.0",
    "pandas>=2.2",
    "matplotlib>=3.9",
    "scikit-learn>=1.5"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "ruff>=0.8"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 88
target-version = "py311"